### ISSUE TITLE
Docker container fails to launch browser on startup.

### ISSUE THREAD

**Issue by shinysocks** [drizzle-mizzle/CharacterAI-Discord-Bot#119]
- [x] I am using the [latest version](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/releases/latest) of the program.
- [x] I have read the [Known-issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues) section and [Issues](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/issues) page, and made sure that this problem was not already described elsewhere.

### Describe the bug:
After cloning this repository and running `docker compose up -d` the container errors.

### Steps to reproduce the behavior:
1. Clone this repo
2. Run with `docker compose up -d`

### Expected behavior:
The container should run the same as when the discord bot is launched with ./CharacterDiscordBot

### System Info
![image](https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot/assets/91911303/f40e778c-fdfe-4adb-8a16-47fae0e802a5)

### Error Log from Container
`2023-06-13T02:53:39.082169077Z 02:53:39 Discord     Discord.Net v3.10.0 (API v10)
2023-06-13T02:53:39.102170444Z 02:53:39 Gateway     Connecting
2023-06-13T02:53:40.016599244Z 02:53:40 Gateway     Connected
2023-06-13T02:53:40.514808989Z 02:53:40 Gateway     Ready
2023-06-13T02:53:40.531294496Z 
2023-06-13T02:53:40.531329761Z It may take some time on the first launch, because it will need to download a Chrome executable (~450mb).
2023-06-13T02:53:40.531334555Z If this process takes too much time, ensure you have a good internet connection (timeout = 20 minutes).
2023-06-13T02:53:40.531337440Z 
2023-06-13T02:53:44.499190902Z Downloading browser... OK
2023-06-13T02:53:44.508381269Z 
2023-06-13T02:53:44.508427537Z (If it hangs on for some reason, just try to relaunch the application)
2023-06-13T02:53:44.572651993Z Launching browser... PuppeteerSharp.ProcessException: Failed to launch browser! 
2023-06-13T02:53:44.572677338Z    at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ChromiumStartingState.cs:line 83
2023-06-13T02:53:44.572680548Z    at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/States/ChromiumStartingState.cs:line 89
2023-06-13T02:53:44.572683276Z    at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 62
2023-06-13T02:53:44.572685915Z    at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Launcher.cs:line 95
2023-06-13T02:53:44.572688505Z    at PuppeteerExtraSharp.PuppeteerExtra.LaunchAsync(LaunchOptions options)
2023-06-13T02:53:44.572691198Z    at CharacterAI.Integration.LaunchChromeAsync(String customChromeDir, String customExecPath)
2023-06-13T03:03:34.341988856Z    at CharacterAI_Discord_Bot.Program.LaunchChromeAndSetup(Boolean setup) in /app/Program.cs:line 57`

**Comment by shinysocks** [comment]
Alright, I'll take a look at it.

**Comment by shinysocks** [comment]
I submitted a pull request, check it out.
