### ISSUE TITLE
[Help]Docker build fails (solved)

### ISSUE THREAD

**Issue by UnconsciousPebble** [drizzle-mizzle/CharacterAI-Discord-Bot#137]
I'm installed the bot into a docker image using
`docker build -t username .`

the build seemed to be successful, and the image shows up in my list, but after running it with` "docker run" ` I'm getting the following error:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'CharacterAI_Discord_Bot.Service.CommonService' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CharacterAI_Discord_Bot.Service.CommonService.Failure(String logText, HttpResponseMessage response, DiscordSocketClient client) in /app/Service/CommonService.cs:line 252
   at CharacterAI_Discord_Bot.Service.CommonService.GetConfig() in /app/Service/CommonService.cs:line 278
   at CharacterAI_Discord_Bot.Service.CommonService..cctor() in /app/Service/CommonService.cs:line 15
   --- End of inner exception stack trace ---
   at CharacterAI_Discord_Bot.Service.CommonService.get_BotConfig() in /app/Service/CommonService.cs:line 13
   at CharacterAI_Discord_Bot.Program.MainAsync() in /app/Program.cs:line 23
   at CharacterAI_Discord_Bot.Program.Main() in /app/Program.cs:line 16
./entrypoint.sh: line 2:     8 Aborted                 ./CharacterAI_Discord_Bot
```
I'm new to docker, so I was wondering if I just messed something up or there is a problem with the docker buildfile?

### Additional info:
- Windows10 22H2
- Docker Engine v24.0.2 (WSL edition)

**Comment by drizzle-mizzle** [comment]
It's not docker error, there's something with you config file

**Comment by UnconsciousPebble** [comment]
Indeed, I noticed that I forgot to update to the last version and didn't
update the config until now.
 Thanks for your help, and sorry for the trouble.
