### ISSUE TITLE
[ISSUE]  System.Exception: WebSocket connection was closed

### ISSUE THREAD

**Issue by LProjectLight** [drizzle-mizzle/CharacterAI-Discord-Bot#15]
17:15:51 Discord     Discord.Net v3.8.1 (API v10)
17:15:51 Gateway     Connecting
17:15:53 Gateway     System.Exception: WebSocket connection was closed
 ---> Discord.Net.WebSocketClosedException: The server sent close 4014: "Disallowed intent(s)."
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.WaitAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
17:15:53 Gateway     Disconnecting
17:15:53 Gateway     Disconnected

**Comment by drizzle-mizzle** [comment]
You forgot to enable Privileged Gateway Intents.
