### ISSUE TITLE
I already checked 'Privileged Gateway Intents' options in my developer page, but it dosen't work

### ISSUE THREAD

**Issue by AmazingSSUE** [drizzle-mizzle/CharacterAI-Discord-Bot#47]
I opened .exe file, it goes

13:36:03 Discord     Discord.Net v3.9.0 (API v10)
13:36:03 Gateway     Connecting
13:36:04 Gateway     Ready
13:36:04 Gateway     You're using the GuildPresences intent without listening to the PresenceUpdate event, consider removing the intent from your config.
13:36:04 Gateway     Connected

I allowed these options in developer page.
PRESENCE INTENT
SERVER MEMBERS INTENT
MESSAGE CONTENT INTENT

need some help :(

**Comment by drizzle-mizzle** [comment]
That's not a error. Is says that there's no need for bot to listen to this intent, but it's actually being used in program.
Though, bot is not working now, check readme.

**Comment by AmazingSSUE** [comment]
Thank you for help! <3
And I have a question, should I keep running program while I using this bot? Or it's done with once I run .exe file? 

Sorry for poor English :(

**Comment by drizzle-mizzle** [comment]
Of cource bot will stop working if you close it. 
If you want to run any program in background, you'll need to run it as a service.

**Comment by AmazingSSUE** [comment]
I got this problem, (I already read the prior case in 401 issues. but nevertheless i put a correct bot token, it doesn't working yet.) can you give me sone advice again? I invited my bot account in my server.

When i run the .exe file

01:41:44 Discord     Discord.Net v3.9.0 (API v10)
01:41:44 Discord     A supplied token was invalid.:
System.ArgumentException: A Bot token must be at least 58 characters in length. Ensure that the Bot Token provided is not an OAuth client secret. (Parameter 'token')
   at Discord.TokenUtils.ValidateToken(TokenType tokenType, String token)
   at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token, Boolean validateToken)
01:41:44 Gateway     Connecting
01:41:44 Gateway     Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.GetBotGatewayAsync(RequestOptions options)
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()
   at Discord.API.DiscordSocketApiClient.ConnectAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
01:41:44 Gateway     Disconnecting
01:41:44 Gateway     Disconnected


Here is my setting


![화면 캡처 2023-03-27 014443](https://user-images.githubusercontent.com/128569300/227791026-ac3fa987-ef98-4ef1-9751-66ebd2bab488.png)

![화면 캡처 2023-03-27 014603](https://user-images.githubusercontent.com/128569300/227791035-c7980b25-1cbb-4d19-bfdb-bf031378fe35.png)


I don't know about where I have to fix... Sorry for many questions :=(

**Comment by drizzle-mizzle** [comment]
I wouldn't recommend to bother right. As I said, it's not working now anyway, like at all.

**Comment by drizzle-mizzle** [comment]
About your problem, I think that what error says – is exactly what happened 
> A Bot token must be at least 58 characters in length. Ensure that the Bot Token provided is not an OAuth client secret.

**Comment by drizzle-mizzle** [comment]
Maybe you mixed up bot token and  character ai user token in Config file

**Comment by AmazingSSUE** [comment]
Isn't it correct? Check my edit please.. (I already reset my bot  token! I should delete this comment if it needs.)


![화면 캡처 2023-03-27 021412](https://user-images.githubusercontent.com/128569300/227792565-6b9062fb-5d76-4a1f-9cdf-54d114badb26.png)

**Comment by drizzle-mizzle** [comment]
Seems correct. In open post logs it seems like you launched it without any problems before... strange

**Comment by drizzle-mizzle** [comment]
Also, if you use some public wifi, or VPN, it can also cause a problems

**Comment by AmazingSSUE** [comment]
I using a public wifi. What should I have to use another?

**Comment by drizzle-mizzle** [comment]
Amm... I mean, a public WiFi in university/work or something like this. If it's your own one, it's fine.

**Comment by AmazingSSUE** [comment]
Thank you so much for helps!!! :3
I'll try this in my home! Thanks Miz <3

**Comment by drizzle-mizzle** [comment]
Does it works now? Download last update and check it out.
