### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by multicody10** [drizzle-mizzle/CharacterAI-Discord-Bot#61]
00:16:35 Gateway     A MessageReceived handler has thrown an unhandled exception.:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at CharacterAI_Discord_Bot.Handlers.CommandsHandler.HandleMessage(SocketMessage rawMsg)
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)

**Comment by drizzle-mizzle** [comment]
https://github.com/drizzle-mizzle/CharacterAI-Discord-Bot#known-issues
