### ISSUE TITLE
Failed to generate the bucket id for this operation.

### ISSUE THREAD

**Issue by MiwieWasabi** [drizzle-mizzle/CharacterAI-Discord-Bot#70]
After I launch bot everything seems to be fine. Until I type a command then it got error in console.

```
18:05:33 Gateway     A MessageReceived handler has thrown an unhandled exception.:
System.InvalidOperationException: Failed to generate the bucket id for this operation.
 ---> System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Discord.API.DiscordRestApiClient.CreateBucketId(Expression`1 endpoint)
   --- End of inner exception stack trace ---
   at Discord.API.DiscordRestApiClient.CreateBucketId(Expression`1 endpoint)
   at Discord.API.DiscordRestApiClient.<>c__DisplayClass254_0.<GetBucketId>b__0(String x)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Discord.API.DiscordRestApiClient.GetBucketId(String httpMethod, BucketIds ids, Expression`1 endpointExpr, String callingMethod)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, Expression`1 endpointExpr, Object payload, BucketIds ids, ClientBucketType clientBucket, RequestOptions options, String funcName)
   at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, AllowedMentions allowedMentions, MessageReference messageReference, MessageComponent components, ISticker[] stickers, RequestOptions options, Embed[] embeds, MessageFlags flags)
   at Discord.WebSocket.SocketTextChannel.Discord.IMessageChannel.SendMessageAsync(String text, Boolean isTTS, Embed embed, RequestOptions options, AllowedMentions allowedMentions, MessageReference messageReference, MessageComponent components, ISticker[] stickers, Embed[] embeds, MessageFlags flags)
   at Discord.MessageExtensions.ReplyAsync(IUserMessage msg, String text, Boolean isTTS, Embed embed, AllowedMentions allowedMentions, RequestOptions options, MessageComponent components, ISticker[] stickers, Embed[] embeds)
   at CharacterAI_Discord_Bot.Handlers.CommandsHandler.HandleMessage(SocketMessage rawMsg)
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

**Comment by drizzle-mizzle** [comment]
Don't you execute it too early, before everything is loaded and ready?
Also, check if your bot has been invited on your server properly, with a "bot" checkmark.
