### ISSUE TITLE
System.Net.WebSockets.WebSocketException 

### ISSUE THREAD

**Issue by Sankku76** [drizzle-mizzle/CharacterAI-Discord-Bot#72]
i have a error that says

` ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
20:46:46 Gateway     Disconnecting
20:46:46 Gateway     Disconnected
20:46:47 Gateway     Connecting
20:46:48 Gateway     Resumed previous session
20:46:48 Gateway     You're using the GuildPresences intent without listening to the PresenceUpdate event, consider removing the intent from your config.
20:46:48 Gateway     Connected
20:48:10 Gateway     System.Exception: WebSocket connection was closed`

You know what could cause it?

**Comment by drizzle-mizzle** [comment]
That is not a bot problem, something on you side. Maybe you simply have unstable internet connection.
