### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Streekad** [drizzle-mizzle/CharacterAI-Discord-Bot#78]
getting this issue when i run the exe 

07:43:59 Discord     Discord.Net v3.10.0 (API v10)
07:43:59 Gateway     Connecting
07:44:01 Gateway     System.Exception: WebSocket connection was closed
 ---> Discord.Net.WebSocketClosedException: The server sent close 4014: "Disallowed intent(s)."
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.WaitAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
07:44:01 Gateway     Disconnecting
07:44:01 Gateway     Disconnected

**Comment by drizzle-mizzle** [comment]
![image](https://user-images.githubusercontent.com/55811932/234484007-33c69c1c-2910-4291-9469-80f5768b09de.png)
