### ISSUE TITLE
 System.Exception: WebSocket connection was closed

### ISSUE THREAD

**Issue by Jonbivo** [drizzle-mizzle/CharacterAI-Discord-Bot#82]
Hi, I can't get the bot running any commands. I got this when I open the .exe on windows:

 Discord     Discord.Net v3.10.0 (API v10)
 Gateway     Connecting
 Gateway     System.Exception: WebSocket connection was closed
 ---> Discord.Net.WebSocketClosedException: The server sent close 4014: "Disallowed intent(s)."
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.WaitAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
 Gateway     Disconnecting
 Gateway     Disconnected

**Comment by drizzle-mizzle** [comment]
#78
