### ISSUE TITLE
Keeps on disconnecting

### ISSUE THREAD

**Issue by Xenability** [drizzle-mizzle/CharacterAI-Discord-Bot#86]
idk why but it keeps on doing this:

23:48:14 Discord     Discord.Net v3.10.0 (API v10)
23:48:14 Discord     A supplied token was invalid.:
System.ArgumentException: A Bot token must be at least 58 characters in length. Ensure that the Bot Token provided is not an OAuth client secret. (Parameter 'token')
   at Discord.TokenUtils.ValidateToken(TokenType tokenType, String token)
   at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token, Boolean validateToken)
23:48:14 Gateway     Connecting
23:48:15 Gateway     Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.GetBotGatewayAsync(RequestOptions options)
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()
   at Discord.API.DiscordSocketApiClient.ConnectAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()

**Comment by drizzle-mizzle** [comment]
So you want me to read the error instead of your by myself?..
> Discord A supplied token was invalid.:
System.ArgumentException: A Bot token must be at least 58 characters in length. Ensure that the Bot Token provided is not an OAuth client secret.

**Comment by Xenability** [comment]
Sorry about not reading it, then where should I get the token?

**Comment by Xenability** [comment]
Sorry about not reading the error, I fixed it, but when i enter some commands like find and set character, it keep on giving me this error, and i don't know what does it meant {"detail":"Authentication credentials were not provided."}
