### ISSUE TITLE
5001: Missing Access

### ISSUE THREAD

**Issue by Bluepeltz** [drizzle-mizzle/CharacterAI-Discord-Bot#87]
I added all the gateway intents and gave it admin priveleges, what's happening:

19:06:29 Gateway     A ReactionAdded handler has thrown an unhandled exception.:
Discord.Net.HttpException: The server responded with error 50001: Missing Access
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.GetChannelMessageAsync(UInt64 channelId, UInt64 messageId, RequestOptions options)
   at Discord.Rest.ChannelHelper.GetMessageAsync(IMessageChannel channel, BaseDiscordClient client, UInt64 id, RequestOptions options)
   at Discord.WebSocket.SocketTextChannel.GetMessageAsync(UInt64 id, RequestOptions options)
   at Discord.WebSocket.SocketTextChannel.Discord.IMessageChannel.GetMessageAsync(UInt64 id, CacheMode mode, RequestOptions options)
   at Discord.WebSocket.DiscordSocketClient.<>c__DisplayClass146_7.<<ProcessMessageAsync>b__18>d.MoveNext()
--- End of stack trace from previous location ---
   at Discord.Cacheable`2.DownloadAsync()
   at CharacterAI_Discord_Bot.Handlers.CommandsHandler.HandleReactionAsync(Cacheable`2 rawMessage, Cacheable`2 channel, SocketReaction reaction)
   at Discord.EventExtensions.InvokeAsync[T1,T2,T3](AsyncEvent`1 eventHandler, T1 arg1, T2 arg2, T3 arg3)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)

**Comment by Bluepeltz** [comment]
Also might be separate issue but it looks like I need to allow cookies and javascript for it to work. I did it in the chromium browser in the files but nothing changed.

![image](https://user-images.githubusercontent.com/102773304/235821963-cbed8292-c588-414e-8c97-4366d84beafd.png)

**Comment by drizzle-mizzle** [comment]
You didn't give the bot all the needed permissions.

**Comment by drizzle-mizzle** [comment]
> Also might be separate issue but it looks like I need to allow cookies and javascript for it to work. I did it in the chromium browser in the files but nothing changed.

You can't do anything about, it's gonna be like this sometimes, when cAI servers are under high load

**Comment by Bluepeltz** [comment]
> You didn't give the bot all the needed permissions.

Theoretically it should work if I check all the boxes listed in the setup, right? I swear I even manually checked all the boxes after selecting bot, but I'll try again.

**Comment by drizzle-mizzle** [comment]
> > You didn't give the bot all the needed permissions.
> 
> Theoretically it should work if I check all the boxes listed in the setup, right? I swear I even manually checked all the boxes after selecting bot, but I'll try again.

You check them before you invite your bot to your server, in link generation page.

**Comment by Bluepeltz** [comment]
Yes in the link generation page there's the bot option to check which give the bot privileges.

**Comment by drizzle-mizzle** [comment]
I don't know what to offer then. If you did everything correctly, it should just work.
Check twice that it actually has all three Privileged Gateway Intents enabled, and try to search something by yourself: https://www.google.com/search?q=The+server+responded+with+error+50001:+Missing+Access+site:stackoverflow.com&sxsrf=APwXEdfHuxjMnfoF4m1xlNJpcF44xzx9Kg:1683093222020&sa=X&ved=2ahUKEwj5_vzsutj-AhU1lMMKHclkBpAQrQIoBHoECAkQBQ

**Comment by Bluepeltz** [comment]
I got rid of the missing access error, but as for the cookies whatever, with the official server bots I notice they connect to characters, but mine is experiencing the high traffic, but some reason your bots don't deal with that? Is there anything I can do to get them that way or not really? Probably not.

**Comment by Bluepeltz** [comment]
I figured it out. It must be my ip is banned or something in something, changed to a vpn and it worked.

**Comment by drizzle-mizzle** [comment]
> I got rid of the missing access error, but as for the cookies whatever, with the official server bots I notice they connect to characters, but mine is experiencing the high traffic, but some reason your bots don't deal with that? Is there anything I can do to get them that way or not really? Probably not.

Explain a bit more please. What are "official servers bots"?

**Comment by drizzle-mizzle** [comment]
Oh, you mean this project server.
Yep, you're right, there's not much I can do right know...
Probably, you are being blocked because you use some popular free vpn, and cloudflare consider it suspicious.

**Comment by Bluepeltz** [comment]
Oddly my regular ip was ok, and turning *on* the VPN is what worked for me. Anyway you can close the issue now.
